### ISSUE TITLE
Preprocessed data? 

### ISSUE THREAD

**Issue by rezacsedu** [MMostavi/CNNCancerType#1]
@MMostavi, are the following files available for research purposes: 

1.    TCGA_new_pre_second.pckl
2.    TCGA_new_pre_first.pckl

**Comment by MMostavi** [comment]
Hi Reza,

I added the link to the data files in the read me.

Good luck

**Comment by rezacsedu** [comment]
@MMostavi, thanks a million.

**Comment by rezacsedu** [comment]
@MMostavi, sorry again. The link you provided is asking for permission. Maybe you want to enable the public link sharing option?

**Comment by MMostavi** [comment]
I just edited the link. I apologize for the inconvenience
