### ISSUE TITLE
5cv_1D_CNN_33class.py  name 'train_labels' is not defined

### ISSUE THREAD

**Issue by xiumu2280** [MMostavi/CNNCancerType#4]
when i  run 5cv_1D_CNN_33class.py， there is an error as follows.

`Traceback (most recent call last):
  File "5cv_1D_CNN_33class.py", line 69, in <module>
    y_s = train_labels
NameError: name 'train_labels' is not defined`

**Comment by MMostavi** [comment]
Thanks for letting me know. I fixed the bug.
